name: Build & Test
on:
  pull_request:
    branches: [ "main", "develop" ]
permissions:
  contents: read
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Clean & Build
        uses: gradle/gradle-build-action@v2
        with:
          arguments: clean assemble
      - name: Lint
        uses: gradle/gradle-build-action@v2
        with:
          arguments: detekt
      - name: Test
        uses: gradle/gradle-build-action@v2
        with:
          arguments: test
