name: Build & Test
on:
  pull_request:
    branches: [ "**" ]
  push:
    branches: [ "develop" ]
permissions:
  contents: read
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: ${{ runner.os }}-gradle-
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Lint
        uses: gradle/gradle-build-action@v2
        with:
          arguments: detekt
      - name: Build
        uses: gradle/gradle-build-action@v2
        with:
          arguments: clean assemble
      - name: Test
        uses: gradle/gradle-build-action@v2
        with:
          arguments: test
